#!/bin/bash

STEAMCMD_UPDATE_SCRIPT_FILENAME="cs2-steamcmd-update-script.sh"
GITHUB_CS2_STEAMCMD_UPDATE_URL="https://raw.githubusercontent.com/GamingHerd/cs_server_setup/main/$STEAMCMD_UPDATE_SCRIPT_FILENAME"
FULL_PACKAGE_UPDATE_SCRIPT_FILENAME="cs2-full-package-update-script.sh"
GITHUB_CS2_FULL_PACKAGE_UPDATE_SCRIPT_URL="https://raw.githubusercontent.com/GamingHerd/cs_server_setup/main/$FULL_PACKAGE_UPDATE_SCRIPT_FILENAME"

cd /home/steam

wget -O "$STEAMCMD_UPDATE_SCRIPT_FILENAME" "$GITHUB_CS2_STEAMCMD_UPDATE_URL"
chmod +x "$STEAMCMD_UPDATE_SCRIPT_FILENAME"

wget -O "$FULL_PACKAGE_UPDATE_SCRIPT_FILENAME" "$GITHUB_CS2_FULL_PACKAGE_UPDATE_SCRIPT_URL"
chmod +x "$FULL_PACKAGE_UPDATE_SCRIPT_FILENAME"
